CREATE TABLE man
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    age      VARCHAR(255),
    location VARCHAR(255),
    CONSTRAINT pk_man PRIMARY KEY (id)
);